// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class Holder
{
    public string HolderId { get; set; }

    public string Manufacturer { get; set; }

    public string PartNumber { get; set; }

    public string Description { get; set; }

    public string Taper { get; set; }

    public double ShankDiameter { get; set; }

    public double Projection { get; set; }

    public virtual ICollection<ToolAssembly> ToolAssemblies { get; set; } = new List<ToolAssembly>();

}