// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class Insert
{
    public string InsertId { get; set; }

    public string Manufacturer { get; set; }

    public string PartNumber { get; set; }

    public string Description { get; set; }

    public string ToolId { get; set; }

    public virtual Tool Tool { get; set; }
}