// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class Machine
{
    public string MachineId { get; set; }

    public string Name { get; set; }

    public string Taper { get; set; }

    public virtual ICollection<MachineTool> MachineTools { get; set; } = new List<MachineTool>();
}