// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class MachineTool
{
    public string MachineToolId { get; set; }

    public string MachineId { get; set; }

    public string ToolAssemblyId { get; set; }

    public int? PocketNumber { get; set; }

    public virtual Machine Machine { get; } 

    public virtual ToolAssembly ToolAssembly { get; set; }
}