// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class Tool
{
    public string ToolId { get; set; }

    public string Manufacturer { get; set; }

    public string PartNumber { get; set; }

    public string Description { get; set; }

    public double UsableLength { get; set; }

    public double CuttingDiameter { get; set; }

    public double ShankDiameter { get; set; }

    public int NumberOfTeeth { get; set; }

    public virtual ICollection<Insert> Inserts { get; set; } = new List<Insert>();

    public virtual ICollection<Screw> Screws { get; set; } = new List<Screw>();

    public virtual ICollection<ToolAssembly> ToolAssemblies { get; set; } = new List<ToolAssembly>();
}