// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToolManager.Models;

public partial class ToolAssembly
{
    public string ToolAssemblyId { get; set; }

    public string ToolId { get; set; }

    public string HolderId { get; set; }

    public virtual Holder Holder { get; set; }

    public virtual ICollection<MachineTool> MachineTools { get; set; } = new List<MachineTool>();

    public virtual Tool Tool { get; set; }
}